config/routes.rb
Softblueprint::Application.routes.draw do
  root "projects#index"

  resources :projects do
    resources :roles
  end
  
  resources :users
  

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :roles, dependent: :destroy # or :delete_all if no callbacks on each role
  
  validates :name, presence: true
end

app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to :project

  validates :name, presence: true
  validates :description, presence: true, length: { minimum: 3 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.all
  end

  def show
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      flash[:notice] = "Project has been created."
      redirect_to @project
    else
      flash[:alert] = "Project has not been created."
      render :new
    end
  end

  def edit
  end

  def update
    if @project.update(project_params)
      flash[:notice] = "Project has been updated."
      redirect_to @project    
    else
      flash[:alert] = "Project has not been updated."
      render :edit
    end
  end

  def destroy
    @project.destroy

    flash[:notice] = "Project has been destroyed."

    redirect_to projects_path    
  end

  private

  def project_params
    params.require(:project).permit(:name, :description)
  end

  def set_project
    @project = Project.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The project you were looking for could not be found."
    redirect_to projects_path
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_project
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  def new
    @role = @project.roles.build #equivalent to: @role = Role.new(project_id: @project.id)
  end

  def create
    @role = @project.roles.build(role_params)
    if @role.save
      flash[:notice] = "Role has been created."
      redirect_to [@project, @role]
    else
      flash[:alert] = "Role has not been created."
      render :new
    end
  end

  def edit
  end

  def update
    if @role.update(role_params)
      flash[:notice] = "Role has been updated."
      redirect_to [@project, @role]
    else
      flash[:alert] = "Role has not been updated."
      render :edit
    end
  end

  def destroy
    @role.destroy

    flash[:notice] = "Role has been deleted."
    
    redirect_to @project
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_role
    @role = @project.roles.find(params[:id])
  end

  def role_params
    params.require(:role).permit(:name, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = "You have signed up successfully."
      redirect_to projects_path
    else
      render :new
    end
  end

  def show
  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Softblueprint</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |key, value| %>
  <div class="flash" id="<%= key %>">
    <%= value %>
  </div>
<% end %>
<nav>
  <%= link_to "Sign up", new_user_path %>
</nav>
<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %>
          prohibited this project from being saved:
      </h2>
      <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </p>
  <%= f.submit %>
<% end %>

app/views/projects/edit.html.erb
<h2>Edit <%= @project.name %></h2>
<br />
<%= render 'form' %>

app/views/projects/index.html.erb
<%= link_to "New Project", new_project_path %>
<h2>Projects</h2>
<br />
<ul>
  <% @projects.each do |project| %>
    <li><%= link_to project.name, project %></li>
  <% end %>
</ul>

app/views/projects/new.html.erb
<h2>New Project</h2>
<br />
<%= render 'form' %>

app/views/projects/show.html.erb
<h2><%= @project.name %></h2>
<%= link_to "Edit Project", edit_project_path(@project) %>
<%= link_to "Delete Project", project_path(@project), method: :delete, data: {confirm: "Are you sure?"} %>
<%= link_to "New Role", new_project_role_path(@project) %>
<ul>
  <% @project.roles.each do |role| %>
    <li>
      #<%= role.id %> - 
      <%= link_to role.name, [@project, role] %>
    </li>
  <% end %>
</ul>

app/views/roles/_form.html.erb
<%= form_for [@project, @role] do |f| %>
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %>
      prohibited this role from being saved:</h2>
      <ul>
        <% @role.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </p>
  <%= f.submit %>
<% end %>

app/views/roles/edit.html.erb
<h2>Edit <%= @role.name %> in <%= @project.name %></h2>
<br />
<%= render 'form' %>

app/views/roles/new.html.erb
<h2>New Role</h2>
<br />
<%= render 'form' %>

app/views/roles/show.html.erb
<div id="role">
  <h2><%= @role.name %></h2>
  <%= simple_format(@role.description) %>
</div>
<%= link_to "Edit Role", [:edit, @project, @role] %>
<%= link_to "Delete Role", [@project, @role], method: :delete, data: { confirm: "Are you sure?"} %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <p>
    <%= f.label :name, "Username" %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <%= f.submit "Sign up" %>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>
<br />
<%= render 'form' %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>